dependencies:
    - qt5-base
    - qt5-declarative
    - qt5-quickcontrols
    - qt5-svg
    - qt5-graphicaleffects
    - cmake
    - extra-cmake-modules
build:
    - cmake {srcdir}
    - make
    - make test
